//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2007LM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOC_BONG
    {
        public int IDHB { get; set; }
        public string TEN { get; set; }
        public double DIEM_HB_CAN_DUOI { get; set; }
        public double DIEM_HB_CAN_TREN { get; set; }
        public decimal MUC_TIEN { get; set; }
    }
}
