//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2007LM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class KET_QUA
    {
        public int ID { get; set; }
        public int IDSV { get; set; }
        public int IDMH { get; set; }
        public Nullable<double> DIEM { get; set; }
    
        public virtual MON_HOC MON_HOC { get; set; }
        public virtual SINH_VIEN SINH_VIEN { get; set; }
    }
}
