//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2007LM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MON_HOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MON_HOC()
        {
            this.KET_QUA = new HashSet<KET_QUA>();
        }
    
        public int ID { get; set; }
        public string TEN { get; set; }
        public Nullable<int> TIN_CHI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KET_QUA> KET_QUA { get; set; }
    }
}
