//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2007LM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINH_VIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SINH_VIEN()
        {
            this.KET_QUA = new HashSet<KET_QUA>();
        }
    
        public int ID { get; set; }
        public int IDL { get; set; }
        public string HO { get; set; }
        public string TEN { get; set; }
        public string DIA_CHI { get; set; }
        public Nullable<System.DateTime> NGAY_SINH { get; set; }
        public Nullable<byte> GIOI_TINH { get; set; }
        public Nullable<double> DTB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KET_QUA> KET_QUA { get; set; }
        public virtual LOP LOP { get; set; }
    }
}
