//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2007LM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TO_CHUC
    {
        public int ID { get; set; }
        public int ID_CHA { get; set; }
        public string TEN { get; set; }
    }
}
