//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2007LM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_THONG_TIN_SINH_VIEN
    {
        public int IDSV { get; set; }
        public string HO_SV { get; set; }
        public string TEN_SV { get; set; }
        public string DIA_CHI { get; set; }
        public Nullable<System.DateTime> NGAY_SINH { get; set; }
        public Nullable<byte> GIOI_TINH { get; set; }
        public int IDL { get; set; }
        public string TEN_LOP { get; set; }
        public string PHONG { get; set; }
        public int IDK { get; set; }
        public string TEN_KHOA { get; set; }
    }
}
