//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net2006MVC.Models.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Releaser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Releaser()
        {
            this.BookTitle = new HashSet<BookTitle>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Mã không được để trống")]
        [MaxLength(10, ErrorMessage = "Mã không được nhiều hơn 10 ký tự")]
        [MinLength(3, ErrorMessage = "Mã không được ít hơn 3 ký tự")]
        public string Code { get; set; }
        [Required(ErrorMessage = "Tên không được để trống")]
        public string Name { get; set; }
        public string Notes { get; set; }
        public Nullable<byte> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookTitle> BookTitle { get; set; }
    }
}
