//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net2006MVC.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermission
    {
        public int Id { get; set; }
        public Nullable<int> MenuPermissionId { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual MenuPermission MenuPermission { get; set; }
        public virtual Role Role { get; set; }
    }
}
